### ISSUE TITLE
Recommending FNA VSCode Template

### ISSUE THREAD

**Issue by toyboot4e** [AnshumanKumar14/Nez-doc#2]
[README.md](https://github.com/AnshumanKumar14/Nez-doc/blob/master/README.md) recommends installing FNA manually, but there is already a [template](https://github.com/prime31/FNA-VSCode-Template) that let us setup *Nez + FNA + VSCode* environment via script. I think it should be a preferred way. Also, we need a guide for windows users to run the (shell) script. (maybe Git Bash is a easy way?)

**Comment by AnshumanKumar14** [comment]
Fixed [Commit details](https://github.com/AnshumanKumar14/Nez-doc/commit/7791da4e486c91fae1f3cef5245fb437e0d844c4)
